title = "Voter Registration"
publishdir = "tmp/public"
verbose = "true"
domain = "http://localhost:1313"
ignoreFiles = [

]

DefaultContentLanguage = "en"
publishDir = "tmp/public"

[languages]
  [languages.en]
  title = "Voter Registration"
  verbose = "true"
  contentDir = "content/en"

  [languages.en.params]
  # [params]
  Owner = "USA.gov"
  Referrer_Short_Code = "voteusa"
  lang = "en"
  language = "english"
  root_path = ""
  register_path = "register"
  domain = "http://localhost:1313"

  [languages.es]
  title = "Inscripción para votar"
  verbose = "true"
  contentDir = "content/es"

  [languages.es.params]
  Owner = "USA.gov"
  Referrer_Short_Code = "voteusa_es"
  lang = "es"
  publishDir = "tmp/public/es"
  language = "spanish"
  root_path = "es/"
  register_path = "registrar"
  domain = "http://localhost:1313"
