title = "Voter Registration"
publishdir = "public"
verbose = "true"
ignoreFiles = [
  "content/registrar/.*",
  "layouts/registrar/.*"
]
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[params]
Owner = "USA.gov"
Referrer_Short_Code = "voteusa"
lang = "en"
language = "english"
root_path = ""
register_path = "register"
