baseurl = "https://vote.usa.gov/"

# Taxnomies used to categorize states and territories by registration type
# ex. registration_types = [ 'by_mail', 'in_person', 'not_needed', 'online' ]
[taxonomies]
registration_type = "registration_types"

[params]
Owner = "USA.gov"
lang = "en-US"
