title = "Voter Registration"
verbose = "true"
publishDir = "public/"
DefaultContentLanguage = "en"
ignoreFiles = [
  "content/registrar/.*",
  "layouts/registrar/.*"
]

[params]
Owner = "USA.gov"
Referrer_Short_Code = "voteusa"
lang = "en"
language = "english"
root_path = ""
register_path = "register"

[languages]
  [languages.en]
  weight =1

  [languages.es]

  title = "Registro de Votantes"
  # publishDir = "public/es/"
  verbose = "true"
  ignoreFiles = [
    "content/register/.*",
    "layouts/register/.*"
  ]

  [languages.es.Params]
  Owner = "USA.gov"
  Referrer_Short_Code = "voteusa_spanish"
  lang = "es"
  language = "spanish"
  root_path = "es/"
  register_path = "registrar"
