title = "Voter Registration"
publishdir = "tmp/public"
verbose = "true"
ignoreFiles = [
  "content/registrar/.*",
  "layouts/registrar/.*"
]

[params]
Owner = "USA.gov"
Referrer_Short_Code = "voteusa"
lang = "en"
language = "english"
root_path = ""
register_path = "register/"
