ignoreFiles = []
publishdir = "tmp/public"
title = "Voter Registration"
verbose = "true"
enableGitInfo = "true"
DefaultContentLanguage = "en"
publishDir = "tmp/public"

[languages]
[languages.en]
contentDir = "content/en"
title = "Voter Registration"
verbose = "true"

[languages.en.params]
# [params]
Owner = "Vote.gov"
Referrer_Short_Code = "voteusa"
lang = "en"
language = "english"
register_path = "register"
root_path = ""

[languages.es]
contentDir = "content/es"
title = "Inscripción para votar"
verbose = "true"

[languages.es.params]
Owner = "Vote.gov"
Referrer_Short_Code = "voteusa_es"
lang = "es"
language = "spanish"
publishDir = "tmp/public/es"
register_path = "registrar"
root_path = "es/"
