title = "Voter Registration"
verbose = "true"
# publishDir = "public/"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
  weight =1
  [languages.en.Params]
  # [params]
  Owner = "USA.gov"
  Referrer_Short_Code = "voteusa"
  lang = "en"
  language = "english"
  root_path = ""
  register_path = "register"

  [languages.es]

  title = "Registro de Votantes"
  verbose = "true"

  [languages.es.Params]
  Owner = "USA.gov"
  Referrer_Short_Code = "voteusa_spanish"
  lang = "es"
  language = "spanish"
  root_path = "es/"
  register_path = "registrar"
